# CFLAGS += -fsanitize=kernel-address

# KASAN configuration
TARGET_DRAM_START := 0x80000000
TARGET_DRAM_END := 0x8fffffff
UART_BASE_ADDRESS := 0x10000000

KASAN_SHADOW_MAPPING_OFFSET := 0x77000000
KASAN_SHADOW_MEMORY_START := 0x87000000
KASAN_SHADOW_MEMORY_SIZE := 0x1000000

# CFLAGS += -mllvm -asan-mapping-offset=$(KASAN_SHADOW_MAPPING_OFFSET)

CFLAGS += -DKASAN_SHADOW_MAPPING_OFFSET=$(KASAN_SHADOW_MAPPING_OFFSET)
CFLAGS += -DKASAN_SHADOW_MEMORY_START=$(KASAN_SHADOW_MEMORY_START)
CFLAGS += -DKASAN_SHADOW_MEMORY_SIZE=$(KASAN_SHADOW_MEMORY_SIZE)

CFLAGS += -DTARGET_DRAM_START=$(TARGET_DRAM_START)
CFLAGS += -DTARGET_DRAM_END=$(TARGET_DRAM_END)
CFLAGS += -DUART_BASE_ADDRESS=$(UART_BASE_ADDRESS)

CFLAGS += -ffreestanding

# KASan-specific compiler options
KASAN_SANITIZE_STACK := 1
KASAN_SANITIZE_GLOBALS := 1

KASAN_CC_FLAGS := -fsanitize=kernel-address
KASAN_CC_FLAGS += -fno-builtin
KASAN_CC_FLAGS += -mllvm -asan-mapping-offset=$(KASAN_SHADOW_MAPPING_OFFSET)
KASAN_CC_FLAGS += -mllvm -asan-instrumentation-with-call-threshold=0
KASAN_CC_FLAGS += -mllvm -asan-stack=$(KASAN_SANITIZE_STACK)
KASAN_CC_FLAGS += -mllvm -asan-globals=$(KASAN_SANITIZE_GLOBALS)
KASAN_CC_FLAGS += -DKASAN_ENABLED

CFLAGS += $(KASAN_CC_FLAGS)
